import { useCallback, useEffect, useMemo, useRef, useState } from 'react'
import { AnimatePresence, motion } from 'framer-motion'
import manifest from '../assets/album/manifest.json'

// Optimized images generated by `npm run album`:
//   thumb/N.webp -> tiny, fast-loading rounds for the mosaic
//   full/N.webp  -> sharp full-size version shown in the lightbox
const thumbModules = import.meta.glob('../assets/album/thumb/*.webp', {
  eager: true,
  query: '?url',
  import: 'default',
}) as Record<string, string>
const fullModules = import.meta.glob('../assets/album/full/*.webp', {
  eager: true,
  query: '?url',
  import: 'default',
}) as Record<string, string>

function sortByNumber(record: Record<string, string>) {
  return Object.keys(record)
    .sort((a, b) => {
      const na = a.match(/(\d+)\.\w+$/)
      const nb = b.match(/(\d+)\.\w+$/)
      if (na && nb) return Number(na[1]) - Number(nb[1])
      return a.localeCompare(b)
    })
    .map((k) => record[k])
}

const thumbs = sortByNumber(thumbModules)
const fulls = sortByNumber(fullModules)

// Map manifest entries by index (n is 1-based, matches the file name N.webp).
type ManifestEntry = { n: number; takenAt: string | null }
const manifestByN = new Map<number, ManifestEntry>(
  (manifest as ManifestEntry[]).map((m) => [m.n, m]),
)

// Pair each thumbnail with its full-size counterpart + taken-date by position.
const photos = thumbs.map((thumb, i) => ({
  thumb,
  full: fulls[i] ?? thumb,
  takenAt: manifestByN.get(i + 1)?.takenAt ?? null,
}))

// Warm one-liners about the moment inside the frame. Grouped by era so an old
// 2017 photo gets an "early days" vibe and a 2026 one feels closer to now — but
// the lines describe the moment itself (a smile, a look, a quiet minute) rather
// than the wedding countdown.
const CAPTIONS_BY_ERA: Record<'early' | 'middle' | 'engaged' | 'recent' | 'unknown', string[]> = {
  // 2017 – 2019
  early: [
    'A smile caught mid-sentence.',
    'One of those easy, unposed minutes.',
    'The kind of laugh you feel later.',
    'Somewhere between shy and grinning.',
    'A quiet moment, softly lit.',
    'Just being — and it looked like this.',
  ],
  // 2020 – 2023
  middle: [
    'Shoulders touching, world elsewhere.',
    'A little joke only they got.',
    'The comfortable kind of silence.',
    'Warm light, warmer company.',
    'Caught mid-laugh again.',
    'Ordinary evening, extraordinary company.',
  ],
  // 2024
  engaged: [
    'That look — nothing else needed saying.',
    'Held close, held gently.',
    'A room full of noise, only each other.',
    'Golden light on two happy faces.',
    'A grin that gave the whole day away.',
    'Wrapped up in the moment.',
  ],
  // 2025 – 2026
  recent: [
    'The kind of smile you can’t fake.',
    'Sun in the eyes, joy on the face.',
    'A frame that speaks without words.',
    'Everything in this photo is love.',
    'Present, together, glowing.',
    'A soft second, kept forever.',
  ],
  unknown: [
    'A quiet frame from somewhere along the way.',
    'One of those moments you don’t forget.',
    'A little piece of the story.',
  ],
}

function eraFor(iso: string | null): keyof typeof CAPTIONS_BY_ERA {
  if (!iso) return 'unknown'
  const year = new Date(iso).getFullYear()
  if (!Number.isFinite(year)) return 'unknown'
  if (year <= 2019) return 'early'
  if (year <= 2023) return 'middle'
  if (year <= 2024) return 'engaged'
  return 'recent'
}

function captionFor(index: number, iso: string | null): string {
  const pool = CAPTIONS_BY_ERA[eraFor(iso)]
  return pool[index % pool.length]
}

// Short "X ago" label — no "Taken", no absolute date, just the distance.
function relativeTaken(iso: string | null): string | null {
  if (!iso) return null
  const then = new Date(iso).getTime()
  if (!Number.isFinite(then)) return null
  const diffMs = Date.now() - then
  if (diffMs < 0) return 'just now'
  const day = 86400000
  const days = Math.floor(diffMs / day)
  if (days <= 0) return 'today'
  if (days === 1) return 'yesterday'
  if (days < 30) return `${days} days ago`
  const months = Math.floor(days / 30)
  if (months < 12) return `${months} month${months === 1 ? '' : 's'} ago`
  const years = Math.floor(days / 365)
  return `${years} year${years === 1 ? '' : 's'} ago`
}

// Repeat the available photos to fill the whole page for now. Add more images by
// running `npm run album` (see scripts/optimize-album.mjs).
const TILE_COUNT = 450
const tiles = photos.length
  ? Array.from({ length: TILE_COUNT }, (_, i) => photos[i % photos.length])
  : []

function goHome() {
  window.location.hash = '#/'
}

export function AlbumPage() {
  const [active, setActive] = useState(0)
  const [lightbox, setLightbox] = useState(false)
  const n = photos.length

  const activePhoto = photos[active]
  const activeCaption = useMemo(
    () => (activePhoto ? captionFor(active, activePhoto.takenAt) : null),
    [active, activePhoto],
  )
  const activeRelative = useMemo(
    () => (activePhoto ? relativeTaken(activePhoto.takenAt) : null),
    [activePhoto],
  )

  // Refs + cached centers for the mouse-following magnify (wave) effect.
  const tileRefs = useRef<(HTMLButtonElement | null)[]>([])
  const centers = useRef<{ x: number; y: number }[]>([])
  // Per-tile animated state we lerp toward the target every frame.
  const tileState = useRef<{ s: number; tx: number; ty: number; b: number }[]>([])
  // Cursor position + whether the pointer is currently over the grid.
  const mouse = useRef<{ x: number; y: number; active: boolean }>({ x: 0, y: 0, active: false })
  const rafRef = useRef<number | null>(null)

  const measure = useCallback(() => {
    centers.current = tileRefs.current.map((el) => {
      if (!el) return { x: 0, y: 0 }
      const r = el.getBoundingClientRect()
      return { x: r.left + r.width / 2, y: r.top + r.height / 2 }
    })
    // Make sure the animated-state array matches the tile count.
    if (tileState.current.length !== tileRefs.current.length) {
      tileState.current = tileRefs.current.map(() => ({ s: 1, tx: 0, ty: 0, b: 1 }))
    }
  }, [])

  useEffect(() => {
    measure()
    window.addEventListener('resize', measure)
    return () => window.removeEventListener('resize', measure)
  }, [measure])

  // One persistent animation loop: every frame we compute each tile's target
  // (scale / radial push / brightness) from the cursor and lerp toward it.
  // When the pointer leaves and everything has settled, the loop stops itself.
  const tick = useCallback(() => {
    const radius = 120 // wider area of influence for a softer feel
    const sigma = radius * 0.55 // gaussian width — controls the bell curve shape
    const maxScale = 1.85
    const minScale = 0.95
    const maxPush = 8 // px each tile drifts outward from the cursor at peak
    const maxBright = 1.35 // brightness at the very center
    const lerp = 0.22 // how fast state catches up to target (0..1)

    const els = tileRefs.current
    const cs = centers.current
    const st = tileState.current
    const { x: mx, y: my, active } = mouse.current

    let stillAnimating = false

    for (let i = 0; i < els.length; i++) {
      const el = els[i]
      const c = cs[i]
      const state = st[i]
      if (!el || !c || !state) continue

      let ts = 1
      let ttx = 0
      let tty = 0
      let tb = 1

      if (active) {
        const dx = c.x - mx
        const dy = c.y - my
        const dist = Math.hypot(dx, dy)
        // Gaussian bell curve: 1 at cursor, ~0 near radius edge.
        const g = Math.exp(-(dist * dist) / (2 * sigma * sigma))
        if (g > 0.002) {
          ts = minScale + (maxScale - minScale) * g
          // Push the tile radially outward from the cursor.
          const norm = dist > 0.5 ? 1 / dist : 0
          const push = maxPush * g
          ttx = dx * norm * push
          tty = dy * norm * push
          tb = 1 + (maxBright - 1) * g
        } else {
          // Just outside the peak — gently zoom out a touch.
          ts = minScale + (1 - minScale) * 0.6
        }
      }

      // Lerp current state toward target for smooth in/out motion.
      state.s += (ts - state.s) * lerp
      state.tx += (ttx - state.tx) * lerp
      state.ty += (tty - state.ty) * lerp
      state.b += (tb - state.b) * lerp

      el.style.transform = `translate3d(${state.tx.toFixed(2)}px, ${state.ty.toFixed(2)}px, 0) scale(${state.s.toFixed(3)})`
      el.style.filter = state.b > 1.005 ? `brightness(${state.b.toFixed(3)})` : ''
      const lift = Math.max(0, state.s - 1)
      el.style.zIndex = lift > 0.02 ? String(10 + Math.round(lift * 40)) : '1'

      if (
        Math.abs(state.s - ts) > 0.002 ||
        Math.abs(state.tx - ttx) > 0.15 ||
        Math.abs(state.ty - tty) > 0.15 ||
        Math.abs(state.b - tb) > 0.003
      ) {
        stillAnimating = true
      }
    }

    if (active || stillAnimating) {
      rafRef.current = requestAnimationFrame(tick)
    } else {
      rafRef.current = null
    }
  }, [])

  const ensureLoop = useCallback(() => {
    if (rafRef.current == null) {
      rafRef.current = requestAnimationFrame(tick)
    }
  }, [tick])

  const onPointerMove = useCallback(
    (e: React.PointerEvent) => {
      mouse.current.x = e.clientX
      mouse.current.y = e.clientY
      mouse.current.active = true
      ensureLoop()
    },
    [ensureLoop],
  )

  const resetWave = useCallback(() => {
    mouse.current.active = false
    ensureLoop()
  }, [ensureLoop])

  useEffect(() => {
    return () => {
      if (rafRef.current) cancelAnimationFrame(rafRef.current)
    }
  }, [])

  const prev = useCallback(() => setActive((i) => (i - 1 + n) % n), [n])
  const next = useCallback(() => setActive((i) => (i + 1) % n), [n])

  const open = (i: number) => {
    setActive(i)
    setLightbox(true)
  }

  // Keyboard navigation for the lightbox.
  useEffect(() => {
    if (!lightbox) return
    const onKey = (e: KeyboardEvent) => {
      if (e.key === 'ArrowLeft') prev()
      else if (e.key === 'ArrowRight') next()
      else if (e.key === 'Escape') setLightbox(false)
    }
    window.addEventListener('keydown', onKey)
    return () => window.removeEventListener('keydown', onKey)
  }, [lightbox, prev, next])

  // Ensure we start at the top of this page.
  useEffect(() => {
    window.scrollTo(0, 0)
  }, [])

  if (n === 0) {
    return (
      <div className="flex min-h-screen flex-col items-center justify-center gap-4 bg-sand-50 px-6 text-center">
        <p className="font-serif text-2xl text-ink">No photos yet</p>
        <p className="max-w-md font-body text-ink/60">
          Drop your images into <code className="rounded bg-sand-200 px-1">src/assets/album/</code> and
          they’ll appear here automatically.
        </p>
        <button
          type="button"
          onClick={goHome}
          className="rounded-full bg-ocean-600 px-6 py-2 font-body text-sm text-sand-50"
        >
          Back home
        </button>
      </div>
    )
  }

  return (
    <div className="flex h-screen flex-col overflow-hidden bg-black">
      {/* Header */}
      <header className="z-30 flex shrink-0 items-center justify-between gap-3 border-b border-white/5 bg-black/70 px-6 py-3 backdrop-blur-md">
        <button
          type="button"
          onClick={goHome}
          className="flex items-center gap-2 font-body text-sm text-white/80 transition hover:text-sunset-400"
        >
          <svg viewBox="0 0 24 24" className="h-4 w-4" fill="none" stroke="currentColor" strokeWidth="2">
            <path d="M15 6l-6 6 6 6" />
          </svg>
          Back
        </button>

        {/* Creative title */}
        <div className="flex flex-col items-center leading-none">
          <span className="mb-1 font-body text-[9px] uppercase tracking-[0.45em] text-sunset-400/80 sm:text-[10px]">
            Lavanya &amp; Azar
          </span>
          <div className="flex items-center gap-2.5">
            <span className="hidden h-px w-8 bg-gradient-to-r from-transparent to-sunset-400/50 sm:block" />
            <h1 className="bg-gradient-to-r from-sunset-400 via-coral to-gold bg-clip-text font-serif text-2xl italic text-transparent drop-shadow-[0_1px_10px_rgba(255,140,80,0.25)] sm:text-3xl">
              Frozen in Time
            </h1>
            <motion.span
              aria-hidden
              animate={{ scale: [1, 1.28, 1] }}
              transition={{ duration: 1.1, repeat: Infinity, ease: 'easeInOut' }}
              className="text-lg sm:text-xl"
            >
              💛
            </motion.span>
            <span className="hidden h-px w-8 bg-gradient-to-l from-transparent to-sunset-400/50 sm:block" />
          </div>
        </div>

        <span className="flex items-center gap-1 rounded-full border border-white/10 bg-white/5 px-3 py-1 font-body text-[11px] tabular-nums text-white/60">
          <svg viewBox="0 0 24 24" className="h-3 w-3 text-sunset-400" fill="none" stroke="currentColor" strokeWidth="2">
            <rect x="3" y="3" width="18" height="18" rx="2" />
            <circle cx="8.5" cy="8.5" r="1.5" />
            <path d="M21 15l-5-5L5 21" />
          </svg>
          {n} photos
        </span>
      </header>

      {/* Full-page mosaic of round photos — fills the viewport without scrolling */}
      <div className="min-h-0 w-full flex-1 overflow-hidden px-1.5 py-2 sm:px-3 sm:py-3">
        <div
          onPointerDown={onPointerMove}
          onPointerMove={onPointerMove}
          onPointerUp={resetWave}
          onPointerLeave={resetWave}
          onPointerCancel={resetWave}
          className="grid touch-none grid-cols-[repeat(auto-fill,minmax(28px,1fr))] gap-1 sm:grid-cols-[repeat(auto-fill,minmax(38px,1fr))] sm:gap-1.5"
        >
          {tiles.map((photo, i) => (
            <button
              key={`${i}-${photo.thumb}`}
              ref={(el) => {
                tileRefs.current[i] = el
              }}
              type="button"
              onClick={() => open(i % n)}
              aria-label={`Open photo ${(i % n) + 1}`}
              style={{ willChange: 'transform, filter' }}
              className="group relative aspect-square overflow-hidden rounded-full border border-white shadow-sm ring-1 ring-sand-200 hover:shadow-lg"
            >
              <img
                src={photo.thumb}
                alt={`Album photo ${(i % n) + 1}`}
                loading="lazy"
                decoding="async"
                className="h-full w-full object-cover"
              />
              <span className="pointer-events-none absolute inset-0 rounded-full bg-sunset-500/0 transition-colors group-hover:bg-sunset-500/10" />
            </button>
          ))}
        </div>
      </div>

      {/* Lightbox */}
      <AnimatePresence>
        {lightbox && (
          <motion.div
            className="fixed inset-0 z-50 flex items-center justify-center bg-black/90 p-4"
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            onClick={() => setLightbox(false)}
          >
            <button
              type="button"
              onClick={() => setLightbox(false)}
              aria-label="Close"
              className="absolute right-4 top-4 flex h-11 w-11 items-center justify-center rounded-full bg-white/10 text-white transition hover:bg-white/20"
            >
              <svg viewBox="0 0 24 24" className="h-6 w-6" fill="none" stroke="currentColor" strokeWidth="2">
                <path d="M6 6l12 12M18 6L6 18" />
              </svg>
            </button>

            <button
              type="button"
              onClick={(e) => {
                e.stopPropagation()
                prev()
              }}
              aria-label="Previous photo"
              className="absolute left-4 flex h-12 w-12 items-center justify-center rounded-full bg-white/10 text-white transition hover:bg-white/20"
            >
              <svg viewBox="0 0 24 24" className="h-6 w-6" fill="none" stroke="currentColor" strokeWidth="2">
                <path d="M15 6l-6 6 6 6" />
              </svg>
            </button>

            <motion.img
              key={active}
              src={photos[active].full}
              alt={`Album photo ${active + 1}`}
              initial={{ opacity: 0, scale: 0.96 }}
              animate={{ opacity: 1, scale: 1 }}
              transition={{ duration: 0.3 }}
              onClick={(e) => e.stopPropagation()}
              className="max-h-[85vh] max-w-[90vw] rounded-2xl object-contain shadow-2xl"
            />

            <button
              type="button"
              onClick={(e) => {
                e.stopPropagation()
                next()
              }}
              aria-label="Next photo"
              className="absolute right-4 flex h-12 w-12 items-center justify-center rounded-full bg-white/10 text-white transition hover:bg-white/20"
            >
              <svg viewBox="0 0 24 24" className="h-6 w-6" fill="none" stroke="currentColor" strokeWidth="2">
                <path d="M9 6l6 6-6 6" />
              </svg>
            </button>

            {/* Caption + date banner — solid dark backdrop so text is legible on any photo */}
            <div className="pointer-events-none absolute inset-x-0 bottom-0 flex justify-center pb-4 sm:pb-6">
              <div className="max-w-[92vw] rounded-2xl border border-gold/25 bg-black/70 px-5 py-3 text-center shadow-[0_8px_28px_rgba(0,0,0,0.55)] backdrop-blur-md sm:px-7 sm:py-3.5">
                {activeCaption && (
                  <p className="bg-gradient-to-r from-gold via-sunset-400 to-coral bg-clip-text font-serif text-base italic text-transparent sm:text-lg">
                    “{activeCaption}”
                  </p>
                )}
                <p className="mt-1 flex items-center justify-center gap-2 font-body text-[10px] uppercase tracking-[0.3em] text-gold sm:text-[11px]">
                  {activeRelative && <span>{activeRelative}</span>}
                  {activeRelative && <span className="text-gold/40">·</span>}
                  <span className="tabular-nums text-sand-100/80">
                    {active + 1} / {n}
                  </span>
                </p>
              </div>
            </div>
          </motion.div>
        )}
      </AnimatePresence>
    </div>
  )
}
